version: "3.1"
services:
  airflow-webserver:
    container_name: airflow-webserver
    image: puckel/docker-airflow
    ports:
      - "8080:8080"
    restart: always
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DEFAULT_TIMEZONE="Asia/Taipei"
    volumes:
      - ./dags:/usr/local/airflow/dags
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    # volumes:
    #   - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

networks:
  default:
    driver: bridge
